/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#503c07',
        'on-secondary': '#fff7f5',
        'on-error': '#fff7f6',
        'surface-variant': '#f6ddd5',
        'surface-container-high': '#fae4dc',
        'surface-container-highest': '#f6ddd5',
        'inverse-on-surface': '#a79a96',
        'tertiary-container': '#ffdf9b',
        'background': '#fff8f6',
        'surface': '#fff8f6',
        'on-surface-variant': '#6d5b55',
        'on-primary': '#fff7f5',
        'primary-fixed-dim': '#e65200',
        'on-secondary-fixed': '#55392e',
        'tertiary-fixed-dim': '#f0d18e',
        'on-surface': '#3e2f2a',
        'on-tertiary': '#fff8f0',
        'surface-dim': '#edd5cd',
        'secondary-container': '#ffdbce',
        'error-dim': '#67040d',
        'on-secondary-fixed-variant': '#745449',
        'secondary-dim': '#6a4c41',
        'on-primary-fixed': '#000000',
        'surface-tint': '#a93a00',
        'on-primary-container': '#220600',
        'primary-container': '#fc5b00',
        'on-tertiary-container': '#644f19',
        'surface-container': '#feeae3',
        'primary': '#a93a00',
        'inverse-surface': '#130d0a',
        'inverse-primary': '#fc5b00',
        'primary-dim': '#943200',
        'tertiary-fixed': '#ffdf9b',
        'on-tertiary-fixed-variant': '#6f5822',
        'surface-container-lowest': '#ffffff',
        'secondary': '#78584c',
        'tertiary': '#735c25',
        'tertiary-dim': '#66501a',
        'secondary-fixed-dim': '#f6cbbc',
        'on-secondary-container': '#694b3f',
        'on-primary-fixed-variant': '#380e00',
        'secondary-fixed': '#ffdbce',
        'surface-bright': '#fff8f6',
        'on-error-container': '#6e0a12',
        'primary-fixed': '#fc5b00',
        'on-background': '#3e2f2a',
        'error': '#a83836',
        'error-container': '#fa746f',
        'surface-container-low': '#fff1ec',
        'outline-variant': '#c3ada6',
        'outline': '#8a7770',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '9999px',
      },
      fontFamily: {
        'headline': ['Source Serif 4', 'serif'],
        'body': ['Source Serif 4', 'serif'],
        'label': ['Source Serif 4', 'serif'],
      },
    },
  },
  plugins: [],
}

module.exports = config
